version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solana-faucet-backend
    restart: unless-stopped
    environment:
      - FAUCET_SERVER_ADDRESS=0.0.0.0
      - FAUCET_SERVER_PORT=8080
      - FAUCET_DB_PATH=/app/data/faucet.db
      - FAUCET_SOLANA_RPC_URL=https://api.testnet.solana.com
      - FAUCET_WALLET_PATH=/app/data/wallet.json
      - FAUCET_CORS_ALLOWED_ORIGINS=*
      - FAUCET_TURNSTILE_SECRET=${TURNSTILE_SECRET_KEY:-your-turnstile-secret-key}
      - FAUCET_TURNSTILE_SITE=${TURNSTILE_SITE_KEY:-your-turnstile-site-key}
      - FAUCET_RATE_LIMIT_REQUESTS=5
      - FAUCET_RATE_LIMIT_DURATION=60
      - FAUCET_CLAIM_COOLDOWN=86400
      - FAUCET_AMOUNT_PER_REQUEST=1.0
      - FAUCET_NETWORK_TYPE=testnet
      - FAUCET_TRANSACTION_TIMEOUT=30
    volumes:
      - faucet-data:/app/data
      - ./wallet/faucet-wallet.json:/app/data/wallet.json
    ports:
      - "8080:8080"
    networks:
      - faucet-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: solana-faucet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - faucet-network

volumes:
  faucet-data:
    name: solana-faucet-data

networks:
  faucet-network:
    name: solana-faucet-network
    driver: bridge 