version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solana-faucet-backend
    restart: unless-stopped
    environment:
      - FAUCET_SERVER_ADDRESS=0.0.0.0
      - FAUCET_SERVER_PORT=8080
      - FAUCET_DB_PATH=/data/faucet.db
      - FAUCET_SOLANA_RPC_URL=https://api.testnet.solana.com
      - FAUCET_WALLET_PATH=/data/wallet.json
      - FAUCET_TURNSTILE_SECRET=${TURNSTILE_SECRET_KEY:-your-turnstile-secret-key}
      - FAUCET_TURNSTILE_SITE=${TURNSTILE_SITE_KEY:-your-turnstile-site-key}
    volumes:
      - faucet-data:/data
    # Expose only to internal network for Nginx proxy
    expose:
      - "8080"
    networks:
      - faucet-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: solana-faucet-frontend
    restart: unless-stopped
    # Expose only to internal network for Nginx proxy
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - faucet-network

  # Nginx for local development and testing
  nginx:
    image: nginx:alpine
    container_name: solana-faucet-nginx
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS (if configured)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro  # For SSL certificates
    depends_on:
      - backend
      - frontend
    networks:
      - faucet-network

volumes:
  faucet-data:
    name: solana-faucet-data

networks:
  faucet-network:
    name: solana-faucet-network
    driver: bridge 